version: "3.7"

services:
  app:
    build: .
    container_name: image-resizer-rh
    deploy: 
      resources:
        limits:
          cpus: "1"
        reservations:
          cpus: "1"
    ports:
      - 5050:5050
    volumes:
      - .:/usr/app
